version: '3'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    environment:
      POSTGRES_DB: widgets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
